import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'sustainable_living_platform.settings')
django.setup()

from core.models import LearningModule, Challenge

def populate():
    LearningModule.objects.all().delete()
    Challenge.objects.all().delete()

    modules = [
        {
            "title": "Introduction to Sustainable Living",
            "description": "Understand the basics of sustainability, exploring concepts like the carbon footprint and why individual actions matter.",
            "content": "<h2>What is Sustainable Living?</h2><p>Sustainable living is a lifestyle that attempts to reduce an individual's or society's use of the Earth's natural resources and personal resources. Practitioners of sustainable living often attempt to reduce their carbon footprint by altering methods of transportation, energy consumption, and diet.</p><h3>The Carbon Footprint</h3><p>Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.</p>"
        },
        {
            "title": "Waste Reduction & Recycling",
            "description": "Learn the 5 R's of waste management: Refuse, Reduce, Reuse, Repurpose, and Recycle.",
            "content": "<h2>The 5 R's</h2><ul><li><strong>Refuse:</strong> Say no to things you don't need, especially single-use plastics.</li><li><strong>Reduce:</strong> Buy only what you need to reduce overall waste.</li><li><strong>Reuse:</strong> Switch to reusable items like bags, bottles, and containers.</li><li><strong>Repurpose:</strong> Find new uses for old items instead of throwing them away.</li><li><strong>Recycle:</strong> Make sure you are recycling properly according to local guidelines.</li></ul><p>By implementing these principles, you can significantly shrink your personal waste footprint.</p>"
        },
        {
            "title": "Energy Conservation at Home",
            "description": "Practical tips for reducing electricity and gas consumption in your house or apartment.",
            "content": "<h2>Why Save Energy?</h2><p>Saving energy reduces the demand for fossil fuels, which decreases the emission of greenhouse gases. It also lowers your utility bills!</p><h3>Actionable Tips:</h3><ul><li>Switch to LED lightbulbs.</li><li>Unplug electronics when not in use (phantom energy).</li><li>Use natural light when possible.</li><li>Adjust your thermostat (lower in winter, higher in summer).</li><li>Wash clothes in cold water.</li></ul>"
        },
        {
            "title": "Sustainable Diets",
            "description": "How your food choices impact the environment and how to eat more sustainably.",
            "content": "<h2>The Environmental Cost of Food</h2><p>Food production is a major driver of greenhouse gas emissions, water use, and deforestation. Meat and dairy production generally have higher environmental footprints than plant-based foods.</p><h3>Eating for the Planet</h3><ul><li>Reduce meat consumption (try Meatless Mondays).</li><li>Buy local and seasonal produce to reduce transportation emissions.</li><li>Minimize food waste by planning meals and storing food properly.</li><li>Start a small compost bin for food scraps.</li></ul>"
        }
    ]

    for m in modules:
        LearningModule.objects.create(**m)

    challenges = [
        {
            "title": "Zero-Waste Grocery Run",
            "description": "Go grocery shopping using only reusable bags and avoid buying any items with single-use plastic packaging.",
            "points": 25
        },
        {
            "title": "Unplug for a Day",
            "description": "Unplug all non-essential electronics and appliances for a full 24 hours to reduce phantom power draw.",
            "points": 15
        },
        {
            "title": "Meatless Week",
            "description": "Commit to eating no meat for 7 consecutive days to lower your dietary carbon footprint.",
            "points": 50
        },
        {
            "title": "Start Composting",
            "description": "Set up a home composting system for your kitchen scraps.",
            "points": 30
        },
        {
            "title": "Walk or Bike Commute",
            "description": "Replace one car trip this week with walking, biking, or taking public transit.",
            "points": 20
        },
        {
            "title": "Short Shower Challenge",
            "description": "Keep your showers under 5 minutes for five consecutive days.",
            "points": 15
        }
    ]

    for c in challenges:
        Challenge.objects.create(**c)

if __name__ == '__main__':
    populate()
