# Generated by Django 5.0.14 on 2026-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_challenge_options_alter_learningmodule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
