# Generated by Django 5.0.14 on 2026-02-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='caption',
        ),
    ]
