# Generated by Django 6.0.4 on 2026-04-30 08:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_avatar_url_userprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-points', '-created_at'], 'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AlterModelOptions(
            name='learningmodule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Learning Module', 'verbose_name_plural': 'Learning Modules'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='repeatable',
            field=models.BooleanField(default=False, help_text='Can users complete this challenge multiple times?'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='estimated_time',
            field=models.IntegerField(default=15, help_text='Estimated time to complete in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(help_text='What does this challenge involve?', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=10, help_text='Reward points for completing this challenge', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='content',
            field=models.TextField(help_text='Detailed content with HTML formatting support'),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='description',
            field=models.TextField(help_text='Brief summary of the module content', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Link to your profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell other users about yourself', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='completed_challenges',
            field=models.ManyToManyField(blank=True, related_name='completed_by_users', to='core.challenge'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='completed_by_users', to='core.learningmodule'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Your city or region', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
