# Generated by Django 5.0.14 on 2026-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_challenge_options_alter_learningmodule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('verification_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('verification_type', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('admin_login', 'Admin Login')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'verification_type'], name='core_emailv_email_ec9248_idx'), models.Index(fields=['-created_at'], name='core_emailv_created_478afd_idx')],
            },
        ),
    ]
